### PR TITLE
translation: russian version of 'donations page'

### PR DESCRIPTION
**Pull request by timtim-ww**
First pull request for Russian translation of SC interface.
Donations page translation commit to check that everything is configured correctly.

### CODE REVIEW

**Comment by thesunshade** [comment]
Looks like all the forward slashes have been escaped. I don't think there is any reason that should be happening. Do you know how that might have gotten in there?

@ihongda, @timtim-ww is the volunteer who has been working on Russian translations of articles for the site. He's going to just do his own PRs from now on.

**Comment by timtim-ww** [comment]
@thesunshade 
Oops, I think that's OmegaT
I'll fix that in a moment, thank you

**Comment by timtim-ww** [comment]
I think that's more like it

**Comment by ihongda** [comment]
Thanks @timtim-ww 🙏🏼 
sàdhu!sàdhu!sàdhu!

**Pull request merged**
