### PR TITLE
Html clean5

### PR DESCRIPTION
**Pull request by Manfredsuttacentral**
Cleanup of Kathavatthu and Puggalapannatti, mostly minor errors.

However, please note: kv12.6 had been split into two and as a result the numbering of the remaining chapters of book 12 changed. I renamed the files, i.e. kv12.8.html to kv12.7.html, etc., as well as the numbering within the files, i.e. "12.8" to "12.7", etc. While I am confident that this works, can you please check these for consistency and also the paragraphing? kv12.10.html should be deleted from SC.

Some chapter headings were also corrected.

In 15.4 a paragraph was missing. Can you please check this too and may be insert a link to "the foregoing"?

### CODE REVIEW

**Comment by Aminah-SC** [comment]
Thank you so much for this! I've been checking over the edits you've made and they look great; much appreciated! 

Just a couple of points:
- there seems to have been an accidental duplication of kv4.9 which has been saved under the filename "1". I've diffed them and they are identical, so it looks like I can just delete it, but wanted to double check with you before doing so.
- with respect to the kv12.6 file split, first of all, thanks so much for highlighting this as it does actually need attention. While I know one of the motivations for this round of edits is to have SC's version match the printed version, in the case file numbering / division SC's scheme must take priority, because translations should correspond with the root texts (ie. the EN kv12.7 should correspond with the PLI kv12.7). By a quick glance I can't be 100% sure, but I think this split leads to a misalignment with SC's Pali files. Would you be able to double check this https://suttacentral.net/kv12.7/pli/ms (onwards) and if necessary restore the numbering and update the PR.

Once again, much thanks.

**Comment by Manfredsuttacentral** [comment]
Dear Aminah,

sorry for the delay, I was busy with Dhammasangani.

As to your points:

- the file named "1" was produced by a ruby  script and can be deleted. I don't know the reason why ruby does this, but have noticed this behaviour previously.

 

- I think it is clear from https://archive.org/details/9194KathavatthuVol.II_201806/page/n171/mode/2up that 12.6. and 12.7 on SC

(https://suttacentral.net/kv12.6/en/aung-rhysdavids and https://suttacentral.net/kv12.7/en/aung-rhysdavids)

should be merged, and https://suttacentral.net/kv12.8/en/aung-rhysdavids "12.8. Of Murder" actually is 12.7 in the Pali.

Not that I can really read Pali, but I happen to remember that "mataram jivitam voropeyya, pitaram jivitam voropeyya",  at the beginning of etc., "12.8. Of Murder" in the Pali, refers to matricide, parricide, Arahanticide. I could not find out how to access VRI's Mahasangiti version, but guess that there is either a mistake in Mahasangiti or an error occurred while importing it to SC.

 

Kind regards,

 

Manfred


 
 

Gesendet: Sonntag, 16. Februar 2020 um 10:11 Uhr
Von: "Aminah" <notifications@github.com>
An: suttacentral/sc-data <sc-data@noreply.github.com>
Cc: Manfredsuttacentral <manfred.wierich@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [suttacentral/sc-data] Html clean5 (#63)


Thank you so much for this! I've been checking over the edits you've made and they look great; much appreciated!

Just a couple of points:


	there seems to have been an accidental duplication of kv4.9 which has been saved under the filename "1". I've diffed them and they are identical, so it looks like I can just delete it, but wanted to double check with you before doing so.
	with respect to the kv12.6 file split, first of all, thanks so much for highlighting this as it does actually need attention. While I know one of the motivations for this round of edits is to have SC's version match the printed version, in the case file numbering / division SC's scheme must take priority, because translations should correspond with the root texts (ie. the EN kv12.7 should correspond with the PLI kv12.7). By a quick glance I can't be 100% sure, but I think this split leads to a misalignment with SC's Pali files. Would you be able to double check this https://suttacentral.net/kv12.7/pli/ms (onwards) and if necessary restore the numbering and update the PR.


Once again, much thanks.

**Comment by Aminah-SC** [comment]
Dear Manfred, thanks so much for looking into this and getting back to me!

I very much appreciate the point you make with respect to Mrs. Rhys Davids' translation, nevertheless, I'm a touch apprehensive about changing the numbering (not least as this may not be the only kv translation on SC; as I say all ID numbers need to be aligned). 

I'm afraid I don't know a great deal about the Abhidhamma, nor possible variations in numbering systems and so on, so have to defer to Bhante @sujato on this one… is it possible that there's been an error and kv12.6. and kv12.7 need to be merged on SC, or is this just an instance where SC's numbers ought to supersede the scheme used by Mrs. Rhys Davids?

Regarding the Dhammasangani, again great thanks for your work, Manfred! :pray:

**Comment by Manfredsuttacentral** [comment]
Dear Aminah,

you and SC are most welcome, of course.

 

Kind regards,

 

Manfred

 
 

Gesendet: Freitag, 21. Februar 2020 um 15:19 Uhr
Von: "Aminah" <notifications@github.com>
An: suttacentral/sc-data <sc-data@noreply.github.com>
Cc: Manfredsuttacentral <manfred.wierich@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [suttacentral/sc-data] Html clean5 (#63)


Dear Manfred, thanks so much for looking into this and getting back to me!

I very much appreciate the point you make with respect to Mrs. Rhys Davids' translation, nevertheless, I'm a touch apprehensive about changing the numbering (not least as this may not be the only kv translation on SC; as I say all ID numbers need to be aligned).

I'm afraid I don't know a great deal about the Abhidhamma, nor possible variations in numbering systems and so on, so have to defer to Bhante @sujato on this one… is it possible that there's been an error and kv12.6. and kv12.7 need to be merged on SC, or is this just an instance where SC's numbers ought to supersede the scheme used by Mrs. Rhys Davids?

Regarding the Dhammasangani, again great thanks for your work, Manfred! 🙏

**Pull request merged**
