### PR TITLE
Modernize spelling of buddhist french terms

### PR DESCRIPTION
**Pull request by PaulPichaureau**
Some buddhist or Indian terms like bhikku, arhat, deva have a different spelling in old french traductions. Nowadays, there is an accepted spelling. See for example: 

- [bhikkhu](https://www.larousse.fr/dictionnaires/francais/bhikkhu/9010) in the french Larousse dictionary.
- [arhat](https://www.larousse.fr/dictionnaires/francais/arhat/5230)
- [deva](https://www.larousse.fr/dictionnaires/francais/deva/24918)

For "arhat" two spelling coexist : "arhat" and "arhant". I've chosen the most frequent (on this date), by checking on google.

@aminah-sc

### CODE REVIEW

**Comment by aminah-sc** [comment]
Hey, @PaulPichaureau thanks so much for your work! Highly appreciated. 

@sujato has there been some prior agreement on the updates to these files? My orientation is to leave translators' work untouched (separating content from presentation). Edits seem reasonable in the instance of obvious isolated typos, but personally I wouldn't amend more than that unless at the request of the translator. Archaic word choices/forms reflect a translation's period and, amongst other things, can in some cases help to keep readers alert to a text's context. 

However, if you've already agree that these sorts of edits should be made, please do merge. I've scrolled through the diff, and as the HTML hasn't been touched, no need to run it through validation.

**Comment by sujato** [comment]
I don't have strong opinions about this, it could be done either way. You raise some valid points, but at the end of the day, I would trust the instincts of the native speaker as to what will work best in context.

**Comment by aminah-sc** [comment]
@sujato Sure. In the first instance, I just wanted to check if there was any priory arrangement. In any case, I've merged it. Again, many thanks, @PaulPichaureau.

**Comment by PaulPichaureau** [comment]
This is not a problem of translation, but a problem of transliteration: the way Indian words has been written for french speaking readers. This transliteration has been normalised recently. I think it's important to use modern way for search, indexation, and so on. 

These old translations has other problems. For example, old words used to describe feeling, mental states, etc. These ones should be discussed carefully before any modification.

**Comment by sujato** [comment]
Sure, I agree, standardizing the spelling is a good idea. We have done the same thing in a few cases with the old translations, their Pali spelling was archaic.

As for changing the translations, better to leave them and do a new generation of translations. That's our focus now, using our Bilara webapp. If you're interested, let us know.

**Pull request merged**
