### PR TITLE
add dpd dic + script

### PR DESCRIPTION
**Pull request by cittadhammo**
I am not sure if this is a good method, it has to be run manually if the dpd dictionaries are updated. Also, the 3 files of the dpd are not all proper dictionaries. They work together according to the Readme.md in the new dpd folder at root level.

### CODE REVIEW

**Comment by thesunshade** [comment]
Yes, the fact that the DPD is in constant flux will be an issue no matter what. Triggering the rebuild each week when the site is rebuilt seems excessive, but having to remember to manually rebuild might not be great either.

BTW, do you know how to make use of this `sc-data` branch in a local build? I can figure out how to run your `suttacentral/suttacentral` but not this one.

**Comment by cittadhammo** [comment]
in the main [readme](https://github.com/cittadhammo/suttacentral?tab=readme-ov-file#changing-the-branchs-the-server-or-staging-server-uses)

Changing the branch(s) the server, or staging server, uses
```
cd /opt/suttacentral
git checkout <code-branch>
cd server/sc-data
git checkout <data-branch>
```
Then run the commands for updating, probably including the `make delete-database` step.

**Comment by cittadhammo** [comment]
I thought it would be better to precombine the files and create a "normal" dictionary. This is what I have done in the last commit.

**Comment by ihongda** [comment]
Thanks, Ven. @cittadhammo 🙏🏼 
I'll merge and test this PR, and then push to `Staging` to test.

**Pull request merged**
