### PR TITLE
Ru translation

### PR DESCRIPTION
**Pull request by timtim-ww**
Translation of home and methodology
Donations translation update

### CODE REVIEW

**Comment by thesunshade** [comment]
Oh, I don't think these should have been done on this repo. They belong in `bilara-data`.

I believe that the files you have modified are generated from those on bilara-data.

**Comment by timtim-ww** [comment]
> Oh, I don't think these should have been done on this repo. They belong in `bilara-data`.
> I believe that the files you have modified are generated from those on bilara-data.

Wow, thank you! how come previously my pull request was merged, when I was figuring things out...

**Comment by thesunshade** [comment]
> how come previously my pull request was merged

Hmm. I don't see that you have any closed prs on this repo. https://github.com/suttacentral/sc-data/pulls?q=is%3Apr+is%3Aclosed+author%3Atim 

Am I missing them? Perhaps HongDa somehow moved them over to `bilara-data` manually? Not sure.

Also, I have recently come to understand that when making prs directly to `bilara-data` that the changes have to be made to both the `published` as well as the `unpublished` branches. I haven't figured out an easy way to do this so I just remind @ihongda to make sure they get put in both places.

**Comment by timtim-ww** [comment]
@thesunshade 

Oh, that's because the profile name is misspelled, it's timtim-ww

Here is the merged PR https://github.com/suttacentral/sc-data/pull/237

I've made PR to bilara-data

**Comment by thesunshade** [comment]
Huh. I have no idea what's happening, then.

**Pull request closed without merging**
